package ihm.panels;

import controleur.Controleur;
import ihm.customComponent.PanelWithImg;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.awt.image.*;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
public class PanelCarteWagon extends javax.swing.JPanel {

    private Controleur ctrl;
    /**
     * Creates new form PanelCarteWagon
     */
    public PanelCarteWagon(Controleur ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListCouleur = new javax.swing.JList<>();
        try 
        {
            panelImgRecto = new PanelWithImg(ImageIO.read(new File("./bin/donnees/images/cartes_joueurs/Locomotive.png")));
            panelImgVerso = new PanelWithImg(ImageIO.read(new File("./bin/donnees/images/cartes_joueurs/Locomotive.png")));    
        }
        catch (IOException e){e.printStackTrace();}
        lblImgVerso = new javax.swing.JLabel();
        lblImgRecto = new javax.swing.JLabel();
        btnChangerImgRecto = new javax.swing.JButton();
        btnChangerImgVerso = new javax.swing.JButton();

        setBackground(new java.awt.Color(68, 71, 90));

        jListCouleur.setModel(new javax.swing.AbstractListModel<Color>() {
            List<Color> lstColor = ctrl.getCouleurs();
            public int getSize() { return lstColor.size(); }
            public Color getElementAt(int i) { return lstColor.get(i); }
        });
        jScrollPane1.setViewportView(jListCouleur);

        javax.swing.GroupLayout panelImgRectoLayout = new javax.swing.GroupLayout(panelImgRecto);
        panelImgRecto.setLayout(panelImgRectoLayout);
        panelImgRectoLayout.setHorizontalGroup(
            panelImgRectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImgRectoLayout.setVerticalGroup(
            panelImgRectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelImgVersoLayout = new javax.swing.GroupLayout(panelImgVerso);
        panelImgVerso.setLayout(panelImgVersoLayout);
        panelImgVersoLayout.setHorizontalGroup(
            panelImgVersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImgVersoLayout.setVerticalGroup(
            panelImgVersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        lblImgVerso.setForeground(new java.awt.Color(255, 255, 255));
        lblImgVerso.setText("Image Verso");

        lblImgRecto.setForeground(new java.awt.Color(255, 255, 255));
        lblImgRecto.setText("Image Recto");

        btnChangerImgRecto.setBackground(new java.awt.Color(40, 42, 54));
        btnChangerImgRecto.setForeground(new java.awt.Color(255, 255, 255));
        btnChangerImgRecto.setText("Changer Image");
        btnChangerImgRecto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangerImgRecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangerImgRectoActionPerformed(evt);
            }
        });

        btnChangerImgVerso.setBackground(new java.awt.Color(40, 42, 54));
        btnChangerImgVerso.setForeground(new java.awt.Color(255, 255, 255));
        btnChangerImgVerso.setText("Changer Image");
        btnChangerImgVerso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangerImgVerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangerImgVersoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImgRecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelImgVerso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImgRecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChangerImgRecto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImgVerso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChangerImgVerso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImgRecto)
                            .addComponent(btnChangerImgRecto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(panelImgRecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImgVerso)
                            .addComponent(btnChangerImgVerso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelImgVerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>                        

    private void btnChangerImgRectoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
		JFileChooser fc = new JFileChooser();
		fc.setFileFilter(new FileNameExtensionFilter("JPG & JPEG & GIF & PNG Images", "jpg", "gif", "png", "jpeg"));
		fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);

		int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION  && fc.getSelectedFile().getPath() != null)
		{
			try
			{
				File fichier = fc.getSelectedFile();
				String extention = fichier.getName().substring(fichier.getName().lastIndexOf('.') + 1);

				if (extention.equals("jpg") || extention.equals("gif") || 
				    extention.equals("png") || extention.equals("jpeg")  )
				{
					BufferedImage img = ImageIO.read(fichier);
                    this.panelImgRecto.setImage(img);
					this.panelImgRecto.repaint();
				}
				else
					JOptionPane.showMessageDialog(this, "Le fichier choisi doit-être au format JPG, GIF, PNG ou JPEG", "Erreur", JOptionPane.ERROR_MESSAGE);         
			}
            catch(IOException ex)
            {
                JOptionPane.showMessageDialog(this, "Le fichier choisi n'est pas une image supportée", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                                  

    private void btnChangerImgVersoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnChangerImgRecto;
    private javax.swing.JButton btnChangerImgVerso;
    private javax.swing.JList<Color> jListCouleur;
    private PanelWithImg panelImgRecto;
    private PanelWithImg panelImgVerso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImgRecto;
    private javax.swing.JLabel lblImgVerso;
    // End of variables declaration                   
}
